chore(build): update bitrise CI configs

diff --git a/bitrise/android.yml b/bitrise/android.yml
--- a/bitrise/android.yml
+++ b/bitrise/android.yml
@@ -21,12 +21,15 @@ workflows:
     before_run:
     - tests
     - _test_builds
+    - _push_cache
   deploy-to-staging:
     after_run: 
     before_run:
-    - primary
+    - tests
+    - _test_builds
     - _semantic_release
     - _make_apk
+    - _push_cache
     - _deploy_to_beta_testers
   _init_install:
     description: Do initial setup
@@ -51,6 +54,7 @@ workflows:
             else
               envman add --key PROCEED_WITH_DEPLOYMENT --value 1
             fi
+    - cache-pull@2.0.1: {}
     - script@1.1.5:
         title: Install Detox Utils
         inputs:
@@ -69,7 +73,6 @@ workflows:
         title: Install npm-cache
         inputs:
         - command: install -g npm-cache
-    - cache-pull@2.0.1: {}
     - script@1.1.5:
         title: npm-cache install
         inputs:
@@ -148,8 +151,9 @@ workflows:
             envman add --key CURRENT_RELEASE_VERSION --value $(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g')
 
             git checkout develop
-            git fetch
-            git pull
+            # we'll enable the following 2 lines if we encounter any problems
+            # git fetch
+            # git pull
 
             semantic-release
 
@@ -165,6 +169,10 @@ workflows:
     - gradle-runner@1.8.0:
         run_if: '{{enveq "PROCEED_WITH_DEPLOYMENT" "1"}}'
         inputs:
+        - apk_file_exclude_filter: |
+            *unaligned.apk
+            *Test*.apk
+            *debug.apk
         - gradle_task: assembleRelease
     - sign-apk@1.2.0:
         run_if: '{{enveq "PROCEED_WITH_DEPLOYMENT" "1"}}'
@@ -181,14 +189,19 @@ workflows:
 
             cd android && ./gradlew assembleDebug
         title: Test Building Android Debug App
-    - cache-push@2.0.3:
-        inputs:
-        - cache_paths: |-
-            ./npm
-            ./.gradle
-            /usr/local/lib/node_modules
   _deploy_to_beta_testers:
     steps:
+    - script@1.1.5:
+        title: Remove Unsigned Release APK from Deploy Directory
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            rm /Users/vagrant/deploy/app-release.apk
     - deploy-to-bitrise-io@1.3.10:
         is_always_run: false
         run_if: '{{enveq "PROCEED_WITH_DEPLOYMENT" "1"}}'
@@ -220,6 +233,19 @@ workflows:
         - image_url_on_error: https://media.giphy.com/media/ZanWL0MNtv3y0/giphy.gif
         - image_url: https://media.giphy.com/media/s2qXK8wAvkHTO/giphy.gif
         - webhook_url: "$SLACK_WEBHOOK_URL"
+  _push_cache:
+    steps:
+    - cache-push@2.0.3:
+        inputs:
+        - ignore_check_on_paths: |-
+            $HOME/.gradle/caches/*.lock
+            $HOME/.gradle/caches/*.bin
+            ./.gradle/*.lock
+            ./.gradle/*.bin
+        - cache_paths: |-
+            ./npm
+            $HOME/.gradle
+            ./.gradle
 app:
   envs:
   - opts:
